### ISSUE TITLE
Provide installable package

### ISSUE THREAD

**Issue by petemounce** [mauve/teamcity-queuestats#1]
I'd love to try this out, but cloning and attempting to build fails because I don't have ant.  I'm not a java developer, so putting together the tools required to build this is a bit of a stretch (unless it turns out I just need a JRE and ant...?).

Please could you provide a link to a built package that I can drop directly into my TeamCity instance, or documentation to describe how I can do that?

**Comment by mauve** [comment]
I have uploaded a built plugin to github which you can download from here: https://github.com/downloads/mauve/teamcity-queuestats/queuestats.zip

Hope it works.

**Comment by petemounce** [comment]
Thanks very much; works fine on TeamCity 6.5.5 on Windows 2008 R2 x64.
